<?php
/*implements
 * hook menu*/
function multistep_example_menu() { 
  $items = array(); 
  $items['multistep_example'] = array(
    'title' => 'Multistep ajax form ',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('multistep_example_form'),
    'access callback' => TRUE,
  );
  $items['admin/config/system/item'] = array(
    'title' => 'Multistep_example module settings', 
    'description' => 'Here you need to write your e-mail address to send a message with answers', 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('multistep_example_admin_form_menu'), 
    'access arguments' => array('administer site configuration'), 
    'type' => MENU_NORMAL_ITEM, 
   ); 
  return $items; 
}
/*
*form to add E-mail */
function multistep_example_admin_form_menu($form,&$form_state){
  $form = array();
  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => '',
    '#size' => '20',
    '#attributes'=>array('placeholder' => t('E-mail address'))
  );
$form['submit']= array(
      '#type' => 'submit', 
      '#value' => 'Save e-mail',
      '#submit' => array('multistep_example_admin_form_submit'));
  return $form;
}
/*
 * Processing admin form */
function multistep_example_admin_form_submit($form, &$form_state){
 global $email;
  if (isset($form_state['values']['email'])) {
    /*save $email */
    $email = variable_set('mail',$form_state['values']['email']);
  drupal_set_message("Your adress is $email saved");
  } else {
    drupal_set_message("type your e-mail");
  }
  return $email;
}
/*
 * General form */
function multistep_example_form($form, &$form_state) {
  $form['#prefix'] = '<div id="multistep-example-form-wrapper">';
  $form['#suffix'] = '</div>';
  $form['#tree'] = TRUE;
  $step = empty($form_state['storage']['step']) ? 1 : $form_state['storage']['step'];
  $form_state['storage']['step'] = $step;
  switch ($step) {
    case 1:    
      $form['step1'] = array(
        '#type' => 'fieldset', 
        '#title' => 'Choose your age and gender.',
      );  
      $form['step1']['age'] = array(
        '#type' => 'select', 
        '#title' => 'Choose your age', 
        '#options' => drupal_map_assoc(array('10-25', '26-50', '51-76', '77-500')),
        '#field_suffix' => 'year',
      );   
      if (isset($form_state['values']['step1']['age'])) {
        $form['step1']['age']['#default_value'] = $form_state['values']['step1']['age'];
      }   
      $form['step1']['sex'] = array(
        '#type' => 'select', 
        '#title' => 'what is your gender:', 
        '#options' => drupal_map_assoc(array('Undefined', 'Male', 'Female')),
      );
      if (isset($form_state['values']['step1']['sex'])) {
        $form['step1']['sex']['#default_value'] = $form_state['values']['step1']['sex'];
      }
      break;
    case 2:
      $form['step2'] = array(
        '#type' => 'fieldset', 
        '#title' => t('Next step.'),
      );
      $default_value = empty($form_state['values']['step2']['color']) ? '' : $form_state['values']['step2']['color'];
      $form['step2']['color'] = array(
        '#type' => 'textfield', 
        '#title' => 'Write your favorite color', 
        '#default_value' => $default_value, 
        '#required' => TRUE,
      );
      $default_value = empty($form_state['values']['step2']['kino']) ? '' : $form_state['values']['step2']['kino'];
      $form['step2']['kino'] = array(
        '#type' => 'textfield', 
        '#title' => 'Write the name of your favorite movie with Chuck Norris:', 
        '#default_value' => $default_value
      );
      break;
    case 3:
      $form['step3'] = array(
        '#type' => 'fieldset', 
        '#title' => 'Last question,are there any movies with Chuck Norris?',
      );
      $form['step3']['film'] = array(
        '#type' => 'checkboxes', 
        '#title' => '',
        '#options' => drupal_map_assoc(array('I do not know who is Chuck Norris', 'Yes of course', 'No', 'I prefer movies with Van Dam')),
        '#required' => TRUE,
      );
      if (isset($form_state['values']['step3']['film'])) {
        $form['step3']['film']['#default_value'] = $form_state['values']['step3']['film'];
      }
      break;
  }  
     
     $form['actions'] = array('#type' => 'actions');
  if ($step == 3) {
    $form['actions']['submit'] = array(
      '#type' => 'submit', 
      '#value' => 'Send e-mail',
    );
  }

  if ($step < 3) {
    $form['actions']['next'] = array(
      '#type' => 'submit', 
      '#value' => 'Next', 
      '#ajax' => array(
        'wrapper' => 'multistep-example-form-wrapper', 
        'callback' => 'multistep_example_ajax_callback',
      ),
    );
  }
  if ($step > 1) {
    $form['actions']['prev'] = array(
      '#type' => 'submit', 
      '#value' => 'Back',       
      '#limit_validation_errors' => array(),
      '#submit' => array('multistep_example_form_submit'), 
      '#ajax' => array(
        'wrapper' => 'multistep-example-form-wrapper', 
        'callback' => 'multistep_example_ajax_callback',
      ),
    );
  }
  return $form;
}
/*
 * ajax processing */
function multistep_example_ajax_callback($form, $form_state) {
  return $form;
}
/*
 * General processing */
function multistep_example_form_submit($form, &$form_state) {
   global $email;
/*Save form*/
  $current_step = 'step' . $form_state['storage']['step'];
  if (!empty($form_state['values'][$current_step])) {
    $form_state['storage']['values'][$current_step] = $form_state['values'][$current_step];
  }

  /*Count*/
  if (isset($form['actions']['next']['#value']) && $form_state['triggering_element']['#value'] == $form['actions']['next']['#value']) {
    $form_state['storage']['step']++;

    $step_name = 'step' . $form_state['storage']['step'];
    if (!empty($form_state['storage']['values'][$step_name])) {
      $form_state['values'][$step_name] = $form_state['storage']['values'][$step_name];
    }
  }
   /*Count back*/
  if (isset($form['actions']['prev']['#value']) && $form_state['triggering_element']['#value'] == $form['actions']['prev']['#value']) {
    $form_state['storage']['step']--;

    $step_name = 'step' . $form_state['storage']['step'];
    $form_state['values'][$step_name] = $form_state['storage']['values'][$step_name];
  }
 /*Processing form */
  if (isset($form['actions']['submit']['#value']) && $form_state['triggering_element']['#value'] == $form['actions']['submit']['#value']) {
    $message = 'Type data is: <br/>';
    foreach ($form_state['storage']['values'] as $step => $values) {
      $message .= "<br/>$step: <br/>";
      foreach ($values as $key => $value) {
        $output = '';
        if (is_array($value)) {
          foreach ($value as $val) {
            $output .= $val ? $val . '; ' : '';
          }
          $value = implode(', ', $value);
        }
        else {
          $output = $value;
        }
        $message .= "$key = $output<br/>";
      }
	  }
    $module = 'multistep_example';
    $key = 'key';
    $language = 'ru';
    $params = array();
    $from = variable_get('site_mail');
    $target_email = variable_get('mail');
    $send = FALSE;
    $mes = drupal_mail($module, $key, $target_email, $language, $params, $from, $send);
    $mes['subject'] = '';
    $mes['body'] = array();
    $mes['body'][] = $message;
    $system = drupal_mail_system($module, $key);
    $mes = $system->format($mes);
    $mes['result'] = $system->mail($mes);
    drupal_set_message("$message send to $target_email");
    $form_state['rebuild'] = FALSE;
    return;
  }

   /*Rebuild form*/
  $form_state['rebuild'] = TRUE;
}

